### ISSUE TITLE
Reason: image not found

### ISSUE THREAD

**Issue by ivanivanusic** [cfriedt/gnuradio-for-mac-without-macports#101]
I've followed steps and when I want to use it with HackRF One, there is error while compiling.

Executing: /Library/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python -u /Users/ivanivanusic/defaultfsdaf.py

Traceback (most recent call last):
  File "/Users/ivanivanusic/defaultfsdaf.py", line 33, in <module>
    import osmosdr
  File "/Applications/GNURadio.app/Contents/MacOS/usr/share/gnuradio/python/site-packages/osmosdr/__init__.py", line 25, in <module>
    from .osmosdr_swig import *
  File "/Applications/GNURadio.app/Contents/MacOS/usr/share/gnuradio/python/site-packages/osmosdr/osmosdr_swig.py", line 13, in <module>
    from . import _osmosdr_swig
ImportError: dlopen(/Applications/GNURadio.app/Contents/MacOS/usr/share/gnuradio/python/site-packages/osmosdr/_osmosdr_swig.so, 2): Library not loaded: /usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/Python
  Referenced from: /Applications/GNURadio.app/Contents/MacOS/usr/share/gnuradio/python/site-packages/osmosdr/_osmosdr_swig.so
  Reason: image not found

>>> Done (return code 1)

**Comment by cloudn1ne** [comment]
same for me

**Comment by phretor** [comment]
Same here.

**Comment by BG7JAF** [comment]
same here with rtlsdr

**Comment by ivanivanusic** [comment]
didnt fixed this
