### ISSUE TITLE
AttributeError: module 'limesdr' has no attribute 'source' on MacOSX

### ISSUE THREAD

**Issue by joelaso** [cfriedt/gnuradio-for-mac-without-macports#95]
Hello all, 

I'm running gnuradio 3.8 on mac OS X 10.15.4.  I have a limeSDR with the following [LimeSDR-USB, media=USB 3.0, module=FX3, addr=1d50:6108, serial=0009081C05C31638].  when adding the sink and source block on my grc I get the following when executing. 

```
Traceback (most recent call last):
  File "/Users/joelquintana/Documents/cSETR/Small Satellite/Francis Building/Ground Station/GNURadio EGSS Version 2.1/flowgraphs/of2_radio_decoder.py", line 319, in <module>
    main()
  File "/Users/joelquintana/Documents/cSETR/Small Satellite/Francis Building/Ground Station/GNURadio EGSS Version 2.1/flowgraphs/of2_radio_decoder.py", line 297, in main
    tb = top_block_cls()
  File "/Users/joelquintana/Documents/cSETR/Small Satellite/Francis Building/Ground Station/GNURadio EGSS Version 2.1/flowgraphs/of2_radio_decoder.py", line 207, in __init__
    self.limesdr_source_0 = limesdr.source('0009081C05C31638', 0, '')
AttributeError: module 'limesdr' has no attribute 'source'

```

I tried a fresh install of gr-limesdr per the instructions on https://wiki.myriadrf.org/Gr-limesdr_Plugin_for_GNURadio with the following error results.  

```
CMake Error at CMakeLists.txt:130 (find_package):
  By not providing "FindGnuradio.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Gnuradio",
  but CMake did not find one.

  Could not find a package configuration file provided by "Gnuradio" with any
  of the following names:

    GnuradioConfig.cmake
    gnuradio-config.cmake

  Add the installation prefix of "Gnuradio" to CMAKE_PREFIX_PATH or set
  "Gnuradio_DIR" to a directory containing one of the above files.  If
  "Gnuradio" provides a separate development package or SDK, be sure it has
  been installed.
```

Thanks again for the help!

**Comment by system123** [comment]
I'm experiencing the same issue

**Comment by system123** [comment]
I have solved this using the following steps:

1) `git clone https://github.com/myriadrf/gr-limesdr.git` into any directory
2) `source /Applications/GNURadio.app/Contents/MacOS/usr/bin/grenv.sh`
3) `cd gr-limesdr`
4) `mkdir build & cd build`
5) `cmake ..`
6) `make`
7) `make install`

This will rebuild and reinstall the limesdr plugin, after which everything works as expected.
